name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get nlohmann/json
        run: |
          choco install wget
          mkdir nlohmann
          wget https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp -o nlohmann/json.hpp

      - name: Build
        shell: bash
        run: |
          g++  ./jap/patch_ga.cpp -o patch_ga.exe -static -O2
          g++  ./jap/patch_li.cpp -o patch_li.exe -static -O2
          g++  ./jap/patch_so.cpp -o patch_so.exe -static -O2
          g++  ./jap/patcher.cpp -o patcher.exe -static -O2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: JustAsPlanned
          path: |
            patch_ga.exe
            patch_li.exe
            patch_so.exe
            patcher.exe
