name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Build
      shell: bash
      run: |
        windres resource.rc -o resource.o
        g++  patch_ga.cpp resource.o -o patch_ga.exe -static
        g++  patch_li.cpp resource.o -o patch_li.exe -static

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JustAsPlanned
        path: |
          patch_ga.exe
          patch_li.exe
