name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get nlohmann/json
        run: |
          choco install 7zip wget --no-progress -y
          mkdir -p jap/nlohmann 
          wget https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp -O jap/nlohmann/json.hpp

      - name: Compile resource file
        run: |
          windres ./jap/resoucre.rc -o resource.o

      - name: Build
        shell: bash
        run: |
          mv ./jap/config.json config.json
          for file in ./jap/*.cpp; do
            exe_name=$(basename "${file%.cpp}.exe")
            g++ "$file" resource.o -o "$exe_name" -static -O2 -I ./jap
          done
          7z a -r JustAsPlanned.zip *.exe config.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: JustAsPlanned
          path: |
            *.exe
            config.json

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: JAP Archive
          make_latest: true
          tag_name: latest
          files: JustAsPlanned.zip
          body: |
            ## Release Notes
            [![Runner](https://img.shields.io/badge/Build-Action-lightgreen?style=for-the-badge&logo=githubactions&logoColor=white)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            💖 **New Update**:  
            - 🛠️ **Bug Fixes**: Fixed some little issues with love and care.  
            - 🚀 **Performance**: Purr-fectly optimized for a smoother experience.  
            - 🎨 **UI Tweaks**: Added a touch of color and love to the output.  

            🥰 Thank you for being awesome! Enjoy the love-filled update! 💫
