name: Nightly Build

on: [push]

permissions:
  contents: write
defaults:
  run:
    working-directory: jap
    shell: bash

jobs:
  nightly:
    name: Nightly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup scripts
        run: |
          pip install -r requirements.txt
          echo $ANDROID_HOME
          ls $ANDROID_HOME/*
          mkdir -p scripts/lib
          cp $ANDROID_HOME/build-tools/36.0.0/lib/apksigner.jar scripts/lib
          cp $ANDROID_HOME/build-tools/36.0.0/apksig* scripts/
          rustup default stable
          cargo install --git https://github.com/Veha0001/Hexsaly
          cp $HOME/.cargo/bin/hexsaly* scripts/hexsaly
      - name: Prepare Archive
        run: zip -r "MUSE_${RUNNER_OS}-${RUNNER_ARCH}_JAP.zip" .
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: MUSE_${{ runner.os }}-${{ runner.arch }}_JAP.zip
          name: Nightly Archive
          tag_name: nightly
          body: |
            # Just As Planned

            Required:
            - Python: 3.10.0^
            - Java: 8^

            ## Patcher

            Windows

            ```pwsh
            .\scripts\hexsaly
            ```

            Unix

            ```sh
            ./scripts/hexsaly
            ```

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
