name: Nightly Build

on: [push, workflow_dispatch]

permissions:
  contents: write
defaults:
  run:
    working-directory: jap
    shell: bash

jobs:
  master:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create Archive
        run: zip -r ../JustAsPlanned.zip .
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: JustAsPlanned.zip
          name: Nightly Archive
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly:
    name: Nightly
    runs-on: ${{ matrix.os }}
    needs: [master]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Setup scripts
        run: |
          mkdir -p scripts/lib
          if [ $RUNNER_OS = "Windows" ]; then
            export ANDROID_HOME="${ANDROID_HOME//\\//}"
          fi
          cp $ANDROID_HOME/build-tools/36.0.0/lib/apksigner.jar scripts/lib
          cp $ANDROID_HOME/build-tools/36.0.0/apksigner* scripts/
          rustup default stable
          cargo install --git https://github.com/Veha0001/Hexsaly
          cp $HOME/.cargo/bin/hexsaly* scripts/
      - name: PyInstaller build
        run: |
          pip install git+https://github.com/Veha0001/DemodAPK
          pip install pillow pyinstaller
          pyinstaller main.spec --workpath=output/build --distpath=output/dist
          rm *.py *.spec
          mv output/dist/* .
          rm -rf output
          rm *.txt
      - name: Prepare Archive
        run: |
          if [ $RUNNER_OS = "Windows" ]; then
            7z a -tzip -r "MUSE_${RUNNER_OS}-${RUNNER_ARCH}_JAP.zip" .
          else
            zip -r "MUSE_${RUNNER_OS}-${RUNNER_ARCH}_JAP.zip" .
          fi
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: ./jap/MUSE_${{ runner.os }}-${{ runner.arch }}_JAP.zip
          name: Nightly Archive
          tag_name: nightly
          body: |
            # Just As Planned

            Required:
            - Python: `3.10.0^`
            - Java: `8^`

            ```bash
            python main.py src/<apk>
            ```

            For more details run with `-h`

            ## Patcher

            Tool: [Hexsaly](https://github.com/Veha0001/Hexsaly)

            ### Windows

            ```pwsh
            .\scripts\hexsaly
            ```

            ### Unix

            ```sh
            ./scripts/hexsaly
            ```

            > [!NOTE]
            > `JustAsPlanned.zip` is `./jap`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
